[tool.ruff]

line-length = 88
target-version = "py313"

exclude = [
    ".venv",
    "venv",
    "__pycache__",
    "alembic",
    "__init__.py",
]

[tool.ruff.lint]

# F: Pyflakes (logic errors)
# E/W: pycodestyle (style errors/warnings)
# I: isort (import sorting)
# B: flake8-bugbear (likely bugs)
# C: flake8-comprehensions (idiomatic comprehensions)
# S: flake8-bandit (security issues)
# Q: flake8-quotes (quote consistency)

select = ["F", "E", "W", "I", "B", "C", "Q"]

# Ignore E501 ("line too long") since formatting tool handles it.
ignore = ["E501"]

[tool.ruff.format]
quote-style = "double"
