"""Initial database setup

Revision ID: d7990743ddfe
Revises:
Create Date: 2025-06-30 20:19:53.928961

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d7990743ddfe"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "crops",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "type",
            sa.Enum(
                "SOYBEAN", "WHEAT", "SUNFLOWER", "CORN", "SORGHUM", name="croptype"
            ),
            nullable=False,
        ),
        sa.Column("brand", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "producers",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_table(
        "harvests",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("producer_id", sa.UUID(), nullable=False),
        sa.Column("crop_id", sa.UUID(), nullable=False),
        sa.Column("harvest_date", sa.Date(), nullable=False),
        sa.Column("quantity_tonnes", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["crop_id"],
            ["crops.id"],
        ),
        sa.ForeignKeyConstraint(
            ["producer_id"],
            ["producers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "sales",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("harvest_id", sa.UUID(), nullable=False),
        sa.Column("sale_date", sa.Date(), nullable=False),
        sa.Column("quantity_sold", sa.Float(), nullable=False),
        sa.Column("price_per_tonne", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["harvest_id"],
            ["harvests.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("sales")
    op.drop_table("harvests")
    op.drop_table("producers")
    op.drop_table("crops")
    # ### end Alembic commands ###
